### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by LxSTx** [eodclan/User-Control-System#22]
Hey, i dont know if the Project is still maintained but with php8.1 there is an Error on "features.php"
Here is the full Error

`Fatal error: Uncaught TypeError: Cannot access offset of type string on string in E:\**\**\UCP\include\features.php:62 Stack trace: #0 E:\xampp\htdocs\UCP\index.php(2): require_once() #1 {main} thrown in E:\**\**\UCP\include\features.php on line 62`

to be honest, i have no clue how to fix it, maybe i can get some help

**Comment by eodclan** [comment]
The error comes from your xampp because xampp is not supported.

**Comment by LxSTx** [comment]
yea i can see, just tried it on my webserver and the error is gone. thank you for the answer! :D
