### ISSUE TITLE
database_mysql.php

### ISSUE THREAD

**Issue by an9n6m97s** [eodclan/User-Control-System#23]
Hello, i got this issue. Anyone can help me?

Warning: mysqli_connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/r102465redl/ucp.redlife.ro/settings/database_mysql.php on line 32

Warning: mysqli_connect(): (HY000/2002): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/r102465redl/ucp.redlife.ro/settings/database_mysql.php on line 32
Connection failed

**Comment by eodclan** [comment]
This UCP is no longer supported.
Use the new UCP from me.
https://github.com/eodclan/xucp

best regards

DerStr1k3r
