### ISSUE TITLE
myprofile.php

### ISSUE THREAD

**Issue by Matetv** [eodclan/User-Control-System#4]
Wenn man sich erfolgreich einloggt und auf "User Profile Chance" klickt, wird man wieder ausgeloggt! 
"You should look first login!"

myprofile.php?myprofile=dashboard

**Comment by Matetv** [comment]
Diese Meldung erschien vor der ersten Registration!
Warning: Cannot modify header information - headers already sent by (output started at /xxxx/themes/default/templates/header.php:127) in /www/htdocs/xxxx/themes/default/templates/header.php on line 133

**Comment by eodclan** [comment]
Installiere dir die V2.5, dann ist das Thema erledigt.
